version: '2'
networks:
  default:
    external:
      name: nginx-proxy

services:
  drupal:
      image: wordpress
      container_name: drupal.${BRANCH_NAME}.localhost
      environment:
        - VIRTUAL_HOST=drupal.${BRANCH_NAME}.localhost