version: '2'
networks:
  default:
    external:
      name: nginx-proxy

services:
  db:
     image: mysql:5.7
     volumes:
       - /var/lib/mysql
     restart: always
     environment:
       - MYSQL_ROOT_PASSWORD=test
       - MYSQL_DATABASE=test
       - MYSQL_USER=test
       - MYSQL_PASSWORD=test
  drupal:
      image: drupal
      container_name: drupal.${BRANCH_NAME}.localhost
      depends_on:
         - db
      environment:
        - VIRTUAL_HOST=drupal.${BRANCH_NAME}.localhost
      volumes:
        - ./code/modules:/var/www/html/modules
        - ./code/themes:/var/www/html/themes
        # this takes advantage of the feature in Docker that a new anonymous
        # volume (which is what we're creating here) will be initialized with the
        # existing content of the image at the same location
       # - ./code/modules:/var/www/html/sites
