version: '2'
networks:
  default:
    external:
      name: nginx-proxy

services:
  drupal:
      image: drupal
      container_name: drupal-${TEST}
      environment:
        - VIRTUAL_HOST=drupal.localhost